## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

dist: xenial

os:
  - linux
  #- osx
  
env:
  
  - JULIA_CMDSTAN_HOME="$HOME/cmdstan-2.26.0/"
before_install:
  - OLDWD=`pwd`
  - cd ~
  - wget https://github.com/stan-dev/cmdstan/releases/download/v2.26.0/cmdstan-2.26.0.tar.gz
  - tar -xzpf cmdstan-2.26.0.tar.gz
  - make -C $JULIA_CMDSTAN_HOME build
  - cd $OLDWD
  

julia:
  - 1.3
  - 1.4
  - 1.5
  - nightly
  
notifications:
  email: false
  
git:
  depth: 99999999

jobs:
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
       - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
       - julia --project=docs --color=yes docs/make.jl
      after_success: skip
  allow_failures:
  - julia: nightly
  - os: osx

after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

